Layout is done
Sportgirl55/IBS-homeworks pull request #1
Opened 2021-06-04 07:20 UTC by Sportgirl55

2021-06-04 10:41 UTC, Roman-Maksimov requested changes

2021-06-04 10:41 UTC, Roman-Maksimov commented on description.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
В данном случае принципиальной разницы нет, но рекомендую всегда помещать вашу таблицу стилей последней. Так у вас будет возможность переопределять third-party стили.

2021-06-04 10:41 UTC, Roman-Maksimov commented on styles.css
> +  max-width: 1400px;
По макету ограничивать ширину контента не требуется. Пусть будет на всю.

2021-06-04 10:41 UTC, Roman-Maksimov commented on styles.css
> +  -o-box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
Тень тут не требуется. На макете её нет.

2021-06-04 10:41 UTC, Roman-Maksimov commented on styles.css
> +  border-bottom: 2px solid var(--orange);
Вы наверняка заметили, что при фокусе на поле, происходит небольшой скачок, из-за того, что раньше границы не было, а потом она появляется толщиной в 2px. По мимо визуального дефекта это еще и приводит к так называемому reflow (пересчету остальных элементов, расположенных ниже этого инпута).
Классически такую задачу решают следующим образом:
```css
.header__input {
  ...
  border-bottom: 2px solid transparent;
  transition: border-color 200ms ease-in;
}

.header__input:focus{
  border-color: var(--orange);
}
```

2021-06-04 10:41 UTC, Roman-Maksimov commented on styles.css
> +  transition: border-bottom 0.2s ease-in;
Помещая transition в :focus, вы включаете анимацию только при переходе `:focus -> :not(:focus)`. В обратную сторону анимации не будет. Стоит перенести transition в основной класс

2021-06-04 10:41 UTC, Roman-Maksimov commented on styles.css
> +  transition: fill 0.2s ease-in;
Аналогично, анимация будет только при снятии фокуса, при установке - не будет. Точнее, некоторые браузеры (например, Chrome) умеют это разруливать, но это скорее вспомогательная фича от производителя браузера, полагаться на это не стоит

2021-06-04 12:48 UTC, Sportgirl55 commented on styles.css
> +  border-bottom: 2px solid var(--orange);
Я предусмотрела этот момент и при фокусе уменьшила высоту элемента, поэтому скачка лично у меня не происходит -  всё остаётся на своём месте.  Но ваше решение и правда отличное!

2021-06-04 15:36 UTC, Roman-Maksimov requested changes

2021-06-04 15:36 UTC, Roman-Maksimov commented on styles.css
> +  border-bottom: 2px solid var(--orange);
достаточно просто `border-color: var(--orange);`

2021-06-04 15:36 UTC, Roman-Maksimov commented on styles.css
> +}
раньше тут был transition, вы его убрали, но я не вижу, чтобы добавили в основной стил иконки

2021-06-08 12:05 UTC, Roman-Maksimov approved these changes

2021-06-08 12:15 UTC, merged